services:
    matching:
        build:
            context: ./matching-service
            dockerfile: Dockerfile
        container_name: matching-service
        env_file:
            - ./matching-service/.env
        ports:
            - "3000:3000" # host 3000 -> container 3000
        restart: unless-stopped

    collab:
        build:
            context: ./collab-service
            dockerfile: Dockerfile
        container_name: collab-service
        env_file:
            - ./collab-service/.env
        volumes:
            - ./collab-level-db:/data/leveldb
        ports:
            - "3002:3000" # host 3002 -> container 3000
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
            interval: 10s
            timeout: 2s
            retries: 5
            start_period: 5s

networks:
    default:
        name: peerprep-net
